import { defineConfig } from 'tsdown'

// Mirrors the `pack` block of sdk/vite.config.ts in GoliathData/sourcing —
// this file is generated by the export, do not edit here.
export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  // Declarations come from `tsc --emitDeclarationOnly` (see package.json build).
  dts: false,
  sourcemap: true,
  clean: false,
  treeshake: true,
  outDir: 'dist',
  hash: false,
  fixedExtension: false,
})
